# Generated by Django 4.0.4 on 2022-05-24 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='id',
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
