# Generated by Django 4.0.4 on 2022-05-24 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0002_remove_package_package_id_remove_tracking_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='unique code for nation')),
                ('name', models.CharField(max_length=100, verbose_name="nation's name")),
                ('leader', models.UUIDField(verbose_name="leader's UUID")),
            ],
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('XPS', 'Pre-Shipment'), ('XRC', 'Received'), ('DTD', 'In Transit (Domestic)'), ('ITD', 'In Transit to Distribution Centre'), ('IWD', 'At Distribution Centre'), ('ITN', 'In Transit to Nation'), ('XFD', 'Delivered')], default='XPS', max_length=3),
        ),
        migrations.AlterField(
            model_name='package',
            name='from_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_nation', to='PostMaster.nation'),
        ),
        migrations.AlterField(
            model_name='package',
            name='to_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_nation', to='PostMaster.nation'),
        ),
    ]
