# Generated by Django 4.0.4 on 2022-05-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0003_nation_alter_tracking_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nation',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='additional notes'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('XPS', 'Pre-Shipment'), ('XRC', 'Received'), ('DTD', 'In Transit (Domestic)'), ('ITD', 'In Transit to Distribution Centre'), ('IWD', 'At Distribution Centre'), ('ITN', 'In Transit to Nation'), ('XFD', 'Delivered')], default='XPS', max_length=3, verbose_name='current status'),
        ),
    ]
