# Generated by Django 4.0.4 on 2022-05-24 04:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0004_nation_notes_alter_tracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nation',
            name='code',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Unique Code for Nation'),
        ),
        migrations.AlterField(
            model_name='nation',
            name='leader',
            field=models.UUIDField(verbose_name="Leader's UUID"),
        ),
        migrations.AlterField(
            model_name='nation',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Nation's Name"),
        ),
        migrations.AlterField(
            model_name='nation',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='package',
            name='delivery_address',
            field=models.CharField(max_length=200, verbose_name='Delivery Address'),
        ),
        migrations.AlterField(
            model_name='package',
            name='from_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='from_nation', to='PostMaster.nation', verbose_name='From Nation'),
        ),
        migrations.AlterField(
            model_name='package',
            name='receiving_date',
            field=models.DateTimeField(verbose_name='Date Received'),
        ),
        migrations.AlterField(
            model_name='package',
            name='return_address',
            field=models.CharField(max_length=200, verbose_name='Return Address'),
        ),
        migrations.AlterField(
            model_name='package',
            name='to_nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='to_nation', to='PostMaster.nation', verbose_name='To Nation'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='status',
            field=models.CharField(choices=[('XPS', 'Pre-Shipment'), ('XRC', 'Received'), ('DTD', 'In Transit (Domestic)'), ('ITD', 'In Transit to Distribution Centre'), ('IWD', 'At Distribution Centre'), ('ITN', 'In Transit to Nation'), ('XFD', 'Delivered')], default='XPS', max_length=3, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='tracking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Tracking Code'),
        ),
    ]
