# Generated by Django 4.0.4 on 2022-05-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0008_alter_tracking_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='has_tracking',
            field=models.BooleanField(default=False, verbose_name='No Tracking'),
        ),
    ]
