# Generated by Django 4.0.4 on 2022-05-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0010_alter_package_has_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='has_tracking',
        ),
    ]
