# Generated by Django 4.0.4 on 2022-05-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0011_remove_package_has_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='has_tracking',
            field=models.BooleanField(default=False, editable=False, verbose_name='No Tracking'),
        ),
    ]
