# Generated by Django 4.0.4 on 2022-05-28 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0012_package_has_tracking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nation',
            options={'verbose_name': 'Nation', 'verbose_name_plural': 'Nations'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'Package', 'verbose_name_plural': 'Packages'},
        ),
        migrations.AlterModelOptions(
            name='tracking',
            options={'verbose_name': 'Tracking', 'verbose_name_plural': 'Tracking'},
        ),
    ]
