# Generated by Django 4.0.4 on 2022-05-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0014_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='UUID',
            field=models.UUIDField(blank=True, verbose_name="Subscriber's UUID"),
        ),
    ]
