# Generated by Django 4.0.4 on 2022-05-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0016_rename_uuid_subscriber_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid',
            field=models.CharField(blank=True, max_length=32, verbose_name="Subscriber's UUID"),
        ),
    ]
