# Generated by Django 4.0.4 on 2022-05-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0017_alter_subscriber_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='uuid_set',
            field=models.BooleanField(default=False, editable=False, verbose_name='No Tracking'),
        ),
    ]
