# Generated by Django 4.0.4 on 2022-05-28 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0018_subscriber_uuid_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='uuid_set',
            field=models.BooleanField(default=False, editable=False, verbose_name='uuid set'),
        ),
    ]
