# Generated by Django 4.0.4 on 2022-05-28 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0019_alter_subscriber_uuid_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='uuid_set',
        ),
    ]
