# Generated by Django 4.0.4 on 2022-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0020_remove_subscriber_uuid_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, editable=False, verbose_name='Welcome email sent'),
        ),
    ]
