# Generated by Django 4.0.4 on 2022-06-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostMaster', '0021_subscriber_welcome_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, to='PostMaster.tracking'),
        ),
    ]
